"""Persistence and audited single-cycle reflection for the constrained Godel-Agent.

Phase 1 of the resident roadmap: durable experiences, a durable candidate
archive that keeps failures, one structured reflection cycle, and human-only
promotion.

Three properties this package deliberately guarantees, and does not offer a way
to opt out of:

* **No automatic promotion.** ``promote`` is invoked by a person. No scheduler,
  flag, or config key promotes a candidate.
* **No holdout evaluation in this process.** Environments load the public split
  and discard the private half; every verdict records
  ``holdout_evaluated=False``. The isolated auditor is Phase 2.
* **AST validation is the first gate, not a sandbox.**
  ``reflect.evaluate_candidate`` is a replaceable seam that Phase 2 turns into a
  resource-limited subprocess runner. It is not containment today.
"""

from __future__ import annotations

import importlib
from typing import Any

#: Submodules reachable as attributes.
_SUBMODULES = ['budget', 'canary', 'serve', 'spool', 'states', 'supervisor']

#: Exported name -> the submodule that defines it.
_EXPORTS = {
    'ANCHORS_DIR_ENV_VAR': 'anchors',
    'AUDIT_FAILED': 'models',
    'AUDIT_OK': 'models',
    'AUDIT_REFUSED': 'models',
    'AlreadyInitializedError': 'promote',
    'ArtifactIntegrityError': 'store',
    'ArtifactMissingError': 'store',
    'AuditError': 'audit',
    'AuditOutcome': 'audit',
    'AuditRecord': 'models',
    'BatchAuditReport': 'audit',
    'BatchOutcome': 'runner',
    'BudgetLimits': 'anchors',
    'CONFIG_DATASET_IDENTITY': 'store',
    'CONFIG_ENVIRONMENT': 'store',
    'CONFIG_THRESHOLD_IDENTITY': 'store',
    'Candidate': 'models',
    'CandidateArchive': 'archive',
    'CandidateRunner': 'runner',
    'Champion': 'models',
    'CycleEvent': 'models',
    'DEFAULT_BATCH_LIMIT': 'audit',
    'DEFAULT_ENVIRONMENT': 'reflect',
    'DatasetIdentity': 'anchors',
    'ENVIRONMENTS': 'reflect',
    'EnvironmentMismatchError': 'store',
    'EnvironmentSpec': 'reflect',
    'EvaluationOutcome': 'runner',
    'Experience': 'models',
    'ExperienceLog': 'experience',
    'FreezeRecord': 'freeze',
    'FrozenError': 'freeze',
    'GATE_SCHEMA_VERSION': 'gate',
    'GateError': 'gate',
    'GateThresholds': 'anchors',
    'GateVerdict': 'gate',
    'InProcessCandidateRunner': 'runner',
    'IsolationProfile': 'runner',
    'KNOWN_OUTCOMES': 'experience',
    'MEMORY_LIMIT_SUPPORTED': 'runner',
    'MIGRATIONS': 'store',
    'MutationProposal': 'mutators',
    'MutationProviderAdapter': 'mutators',
    'MutationRequest': 'mutators',
    'Mutator': 'mutators',
    'PROTOCOL_VERSION': 'runner',
    'PUBLIC_SNAPSHOT_FILENAME': 'store',
    'PromotionError': 'promote',
    'REJECTED_STATUSES': 'models',
    'ReflectionOutcome': 'reflect',
    'ResidentError': 'store',
    'ResidentNotInitializedError': 'store',
    'ResidentStore': 'store',
    'RollbackError': 'rollback',
    'RunnerLimits': 'runner',
    'SCHEMA_VERSION': 'store',
    'SCORED_STATUSES': 'models',
    'STATE_DIR_ENV_VAR': 'store',
    'STATUS_IMPROVEMENT': 'models',
    'STATUS_NO_CANDIDATE': 'models',
    'STATUS_NO_IMPROVEMENT': 'models',
    'STATUS_PROVIDER_ERROR': 'models',
    'STATUS_RETURN_TYPE': 'models',
    'STATUS_RUNTIME': 'models',
    'STATUS_SEED': 'models',
    'STATUS_SYNTAX': 'models',
    'STATUS_VALIDATION': 'models',
    'ScoreVector': 'models',
    'ServingConfig': 'anchors',
    'StateDirectoryError': 'store',
    'StaticMutator': 'mutators',
    'SubprocessCandidateRunner': 'runner',
    'TIER_POLICY': 'models',
    'TIER_PROMPT': 'models',
    'ThresholdError': 'anchors',
    'ThresholdIdentity': 'anchors',
    'UnfreezeError': 'freeze',
    'VETO_NAMES': 'gate',
    'Verdict': 'models',
    'VetoResult': 'gate',
    '_ANCHORS_ENV': 'anchors',
    'active_freeze': 'freeze',
    'assess_ancestors': 'rollback',
    'audit_all_unaudited': 'audit',
    'best_safe_ancestor': 'rollback',
    'bound_environment': 'reflect',
    'build_environment_from_records': 'eval_records',
    'canonicalize_policy': 'store',
    'case_to_record': 'eval_records',
    'dataset_manifest_hash': 'anchors',
    'default_runner': 'reflect',
    'early_rejection_profile': 'runner',
    'evaluate_gate': 'gate',
    'evaluate_policy_source': 'reflect',
    'freeze': 'freeze',
    'get_environment_spec': 'reflect',
    'initialize': 'promote',
    'is_frozen': 'freeze',
    'load_all_anchors': 'anchors',
    'load_anchor_split': 'anchors',
    'load_public_cases': 'reflect',
    'load_thresholds': 'anchors',
    'policy_digest': 'store',
    'promote': 'promote',
    'record_to_case': 'eval_records',
    'reflect_once': 'reflect',
    'require_not_frozen': 'freeze',
    'resolve_anchors_dir': 'anchors',
    'resolve_environment_spec': 'reflect',
    'resolve_state_dir': 'store',
    'rollback': 'rollback',
    'rollback_target_ids': 'rollback',
    'run_audit': 'audit',
    'score_vector_from_result': 'reflect',
    'stable_unit_interval': 'archive',
    'unaudited_candidates': 'audit',
    'unfreeze': 'freeze',
    'write_public_cases': 'reflect',
}


def __getattr__(name: str) -> Any:
    """Import on first use.

    Eagerly importing every submodule here meant that importing *any* one of
    them dragged in the whole package — so the serving process loaded the
    gate, the promoter and the auditor whether or not it could ever call
    them, and the read-only boundary could not be measured. Loading on
    demand makes what a process actually holds a fact rather than a claim.
    """

    if name in _SUBMODULES:
        module = importlib.import_module(f'.{name}', __name__)
        globals()[name] = module
        return module
    origin = _EXPORTS.get(name)
    if origin is None:
        raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
    value = getattr(importlib.import_module(f'.{origin}', __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(__all__) | set(_SUBMODULES))


__all__ = [
    'ANCHORS_DIR_ENV_VAR',
    'AUDIT_FAILED',
    'AUDIT_OK',
    'AUDIT_REFUSED',
    'AlreadyInitializedError',
    'ArtifactIntegrityError',
    'ArtifactMissingError',
    'AuditError',
    'AuditOutcome',
    'AuditRecord',
    'BatchAuditReport',
    'BatchOutcome',
    'BudgetLimits',
    'CONFIG_DATASET_IDENTITY',
    'CONFIG_ENVIRONMENT',
    'CONFIG_THRESHOLD_IDENTITY',
    'Candidate',
    'CandidateArchive',
    'CandidateRunner',
    'Champion',
    'CycleEvent',
    'DEFAULT_BATCH_LIMIT',
    'DEFAULT_ENVIRONMENT',
    'DatasetIdentity',
    'ENVIRONMENTS',
    'EnvironmentMismatchError',
    'EnvironmentSpec',
    'EvaluationOutcome',
    'Experience',
    'ExperienceLog',
    'FreezeRecord',
    'FrozenError',
    'GATE_SCHEMA_VERSION',
    'GateError',
    'GateThresholds',
    'GateVerdict',
    'InProcessCandidateRunner',
    'IsolationProfile',
    'KNOWN_OUTCOMES',
    'MEMORY_LIMIT_SUPPORTED',
    'MIGRATIONS',
    'MutationProposal',
    'MutationProviderAdapter',
    'MutationRequest',
    'Mutator',
    'PROTOCOL_VERSION',
    'PUBLIC_SNAPSHOT_FILENAME',
    'PromotionError',
    'REJECTED_STATUSES',
    'ReflectionOutcome',
    'ResidentError',
    'ResidentNotInitializedError',
    'ResidentStore',
    'RollbackError',
    'RunnerLimits',
    'SCHEMA_VERSION',
    'SCORED_STATUSES',
    'STATE_DIR_ENV_VAR',
    'STATUS_IMPROVEMENT',
    'STATUS_NO_CANDIDATE',
    'STATUS_NO_IMPROVEMENT',
    'STATUS_PROVIDER_ERROR',
    'STATUS_RETURN_TYPE',
    'STATUS_RUNTIME',
    'STATUS_SEED',
    'STATUS_SYNTAX',
    'STATUS_VALIDATION',
    'ScoreVector',
    'ServingConfig',
    'StateDirectoryError',
    'StaticMutator',
    'SubprocessCandidateRunner',
    'TIER_POLICY',
    'TIER_PROMPT',
    'ThresholdError',
    'ThresholdIdentity',
    'UnfreezeError',
    'VETO_NAMES',
    'Verdict',
    'VetoResult',
    'active_freeze',
    'assess_ancestors',
    'audit_all_unaudited',
    'best_safe_ancestor',
    'bound_environment',
    'budget',
    'build_environment_from_records',
    'canary',
    'canonicalize_policy',
    'case_to_record',
    'dataset_manifest_hash',
    'default_runner',
    'early_rejection_profile',
    'evaluate_gate',
    'evaluate_policy_source',
    'freeze',
    'get_environment_spec',
    'initialize',
    'is_frozen',
    'load_all_anchors',
    'load_anchor_split',
    'load_public_cases',
    'load_thresholds',
    'policy_digest',
    'promote',
    'record_to_case',
    'reflect_once',
    'require_not_frozen',
    'resolve_anchors_dir',
    'resolve_environment_spec',
    'resolve_state_dir',
    'rollback',
    'rollback_target_ids',
    'run_audit',
    'score_vector_from_result',
    'serve',
    'spool',
    'stable_unit_interval',
    'states',
    'supervisor',
    'unaudited_candidates',
    'unfreeze',
    'write_public_cases',
]
