"""Wire schema for the holdout audit. Neutral: no controller implementation.

The parent imports validation from here, never from ``auditor_worker``, so the
code that decides what may cross the boundary is separate from the code running
inside it.

The lesson this module encodes: an allowlist of field *names* is not a
boundary. A free-text field on the allowlist is an open channel — holdout
content placed in it crosses and gets persisted exactly like any other string.
So every field here is one of:

* a fixed enum (``status``, ``reason_code``, ``mismatch_field``);
* a value the parent already knows and re-checks for equality
  (``audit_run_id``, ``candidate_id``, ``artifact_hash``, ``dataset_identity``);
* a bounded number, range-checked;
* a mapping whose *keys* come from a set the parent knows independently and
  whose values are finite numbers in range.

There is no free text on the wire at all. Human-readable text in an
``AuditRecord`` is generated by the parent from a reason code, so what gets
persisted is authored on this side of the boundary.
"""

from __future__ import annotations

import json
import math
from typing import Any

from .models import AUDIT_FAILED, AUDIT_OK, AUDIT_REFUSED, AUDIT_STATUSES


AUDIT_PROTOCOL_VERSION = 1
KIND_AUDIT = "audit"

MAX_AUDIT_REQUEST_BYTES = 4 * 1024 * 1024
MAX_AUDIT_RESPONSE_BYTES = 256 * 1024

# --- reason codes -----------------------------------------------------------

REASON_OK = "ok"
REASON_IDENTITY_MISMATCH = "identity_mismatch"
REASON_ANCHOR_UNUSABLE = "anchor_unusable"
REASON_ARTIFACT_MISMATCH = "artifact_mismatch"
REASON_CANDIDATE_TIMEOUT = "candidate_timeout"
REASON_CANDIDATE_RESOURCE_LIMIT = "candidate_resource_limit"
REASON_CANDIDATE_RUNNER_CRASH = "candidate_runner_crash"
REASON_CANDIDATE_PROTOCOL_FAILURE = "candidate_protocol_failure"
REASON_AUDITOR_INTERNAL_FAILURE = "auditor_internal_failure"
#: Parent-generated only. Never accepted from the wire.
REASON_PROTOCOL_FAILURE = "protocol_failure"

WIRE_REASON_CODES = frozenset(
    {
        REASON_OK,
        REASON_IDENTITY_MISMATCH,
        REASON_ANCHOR_UNUSABLE,
        REASON_ARTIFACT_MISMATCH,
        REASON_CANDIDATE_TIMEOUT,
        REASON_CANDIDATE_RESOURCE_LIMIT,
        REASON_CANDIDATE_RUNNER_CRASH,
        REASON_CANDIDATE_PROTOCOL_FAILURE,
        REASON_AUDITOR_INTERNAL_FAILURE,
    }
)
ALL_REASON_CODES = WIRE_REASON_CODES | {REASON_PROTOCOL_FAILURE}

#: Reason codes that may accompany a successful audit.
OK_REASON_CODES = frozenset({REASON_OK})

#: Fixed parent-authored text. The only thing ever written to
#: ``AuditRecord.detail``.
REASON_MESSAGES: dict[str, str] = {
    REASON_OK: "audit completed",
    REASON_IDENTITY_MISMATCH: "anchor dataset does not match the recorded dataset identity",
    REASON_ANCHOR_UNUSABLE: "anchor source could not be read or split",
    REASON_ARTIFACT_MISMATCH: "policy source does not hash to the requested artifact",
    REASON_CANDIDATE_TIMEOUT: "candidate exceeded its wall-clock limit during the audit",
    REASON_CANDIDATE_RESOURCE_LIMIT: "candidate hit a resource limit during the audit",
    REASON_CANDIDATE_RUNNER_CRASH: "candidate execution crashed or could not start",
    REASON_CANDIDATE_PROTOCOL_FAILURE: "candidate execution violated the worker protocol",
    REASON_AUDITOR_INTERNAL_FAILURE: "auditor failed internally",
    REASON_PROTOCOL_FAILURE: "auditor response failed validation and was discarded",
}

#: The only fields of a dataset identity a mismatch may name.
MISMATCH_FIELDS = frozenset(
    {
        "manifest_hash",
        "split_seed",
        "holdout_fraction",
        "total_cases",
        "public_cases",
        "holdout_cases",
    }
)

#: Rubric dimensions defined by ``dataset_env.score_answer``. Keys outside this
#: set are refused, so a mapping key cannot become a text channel.
KNOWN_DIMENSIONS = frozenset(
    {
        "term_coverage",
        "safety",
        "official_channel",
        "actionability",
        "tone_concision",
        "reference_overlap",
    }
)

#: Mechanisms and platforms the isolation profile may name. Anything else
#: normalises to "unknown" rather than being carried across verbatim.
KNOWN_MECHANISMS = frozenset(
    {"subprocess+setrlimit", "in_process", "parent_precheck", "parent_ast_gate", "no_candidate"}
)
KNOWN_PLATFORMS = frozenset({"darwin", "linux", "win32", "cygwin", "aix", "freebsd"})
ENFORCEMENT_VALUES = frozenset({"true", "false", "unknown"})

_ISOLATION_BOOLS = (
    "executed",
    "process_isolated",
    "working_directory_isolated",
    "clean_environment",
    "cpu_limit_requested",
    "memory_limit_requested",
    "file_size_limit_requested",
    "process_count_limit_requested",
    "core_dumps_disabled",
    "filesystem_isolated",
    "network_isolated",
)
_ISOLATION_ENUMS = ("cpu_limit_enforced", "memory_limit_enforced")

RESPONSE_FIELDS = (
    "protocol_version",
    "kind",
    "status",
    "reason_code",
    "mismatch_field",
    "audit_run_id",
    "candidate_id",
    "artifact_hash",
    "holdout_score",
    "num_cases",
    "safety_failure_count",
    "category_means",
    "dimension_means",
    "dataset_identity",
    "isolation",
)


class AuditProtocolError(Exception):
    """Raised when an audit message violates the schema. Always fails closed."""


def message_for(reason_code: str, mismatch_field: str | None = None) -> str:
    """Parent-authored text for a reason code. Never derived from wire strings."""

    base = REASON_MESSAGES.get(reason_code, REASON_MESSAGES[REASON_PROTOCOL_FAILURE])
    if reason_code == REASON_IDENTITY_MISMATCH and mismatch_field in MISMATCH_FIELDS:
        return f"{base} ({mismatch_field})"
    return base


# --- request ----------------------------------------------------------------


def build_audit_request(
    audit_run_id: str,
    candidate_id: str,
    artifact_hash: str,
    policy_source: str,
    environment_name: str,
    anchors_dir: str,
    expected_identity: dict[str, Any],
    limits: dict[str, Any],
) -> dict[str, Any]:
    return {
        "protocol_version": AUDIT_PROTOCOL_VERSION,
        "kind": KIND_AUDIT,
        "audit_run_id": audit_run_id,
        "candidate_id": candidate_id,
        "artifact_hash": artifact_hash,
        "policy_source": policy_source,
        "environment_name": environment_name,
        "anchors_dir": anchors_dir,
        "expected_identity": expected_identity,
        "limits": limits,
    }


def parse_audit_request(raw: bytes) -> dict[str, Any]:
    """Controller side: decode and validate an audit request."""

    if len(raw) > MAX_AUDIT_REQUEST_BYTES:
        raise AuditProtocolError("audit request exceeds the size cap")
    try:
        message = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise AuditProtocolError(f"audit request is not valid JSON: {exc}") from exc
    if not isinstance(message, dict):
        raise AuditProtocolError("audit request is not a JSON object")
    if message.get("protocol_version") != AUDIT_PROTOCOL_VERSION:
        raise AuditProtocolError("audit request protocol_version mismatch")
    if message.get("kind") != KIND_AUDIT:
        raise AuditProtocolError(f"unexpected audit request kind {message.get('kind')!r}")
    for field_name in (
        "audit_run_id",
        "candidate_id",
        "artifact_hash",
        "policy_source",
        "environment_name",
        "anchors_dir",
    ):
        if not isinstance(message.get(field_name), str):
            raise AuditProtocolError(f"{field_name} must be a string")
    if not isinstance(message.get("expected_identity"), dict):
        raise AuditProtocolError("expected_identity must be an object")
    if not isinstance(message.get("limits", {}), dict):
        raise AuditProtocolError("limits must be an object")
    return message


# --- response ---------------------------------------------------------------


def build_audit_response(
    status: str,
    reason_code: str,
    audit_run_id: str,
    candidate_id: str,
    artifact_hash: str,
    mismatch_field: str | None = None,
    holdout_score: float | None = None,
    num_cases: int = 0,
    safety_failure_count: int = 0,
    category_means: dict[str, float] | None = None,
    dimension_means: dict[str, float] | None = None,
    dataset_identity: dict[str, Any] | None = None,
    isolation: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Controller side: assemble a response from the allowlist.

    Note what is absent: there is no field here for a message, an error, an
    exception, or any other string the controller composes. Everything a caller
    might want to say is said with a reason code.
    """

    return {
        "protocol_version": AUDIT_PROTOCOL_VERSION,
        "kind": KIND_AUDIT,
        "status": status,
        "reason_code": reason_code,
        "mismatch_field": mismatch_field,
        "audit_run_id": audit_run_id,
        "candidate_id": candidate_id,
        "artifact_hash": artifact_hash,
        "holdout_score": holdout_score,
        "num_cases": num_cases,
        "safety_failure_count": safety_failure_count,
        "category_means": dict(category_means or {}),
        "dimension_means": dict(dimension_means or {}),
        "dataset_identity": dict(dataset_identity or {}),
        "isolation": dict(isolation or {}),
    }


def normalize_isolation(payload: Any) -> dict[str, Any]:
    """Rebuild an isolation profile from known fields only.

    Booleans must be booleans, enforcement values must be one of three strings,
    and ``mechanism``/``platform`` must be recognised tokens or they become
    ``"unknown"``. Free-text ``notes`` are dropped: they are useful locally but
    have no business crossing a boundary whose whole purpose is to carry no
    prose.
    """

    if not isinstance(payload, dict):
        raise AuditProtocolError("isolation must be an object")

    result: dict[str, Any] = {}
    for name in _ISOLATION_BOOLS:
        value = payload.get(name, False)
        if not isinstance(value, bool):
            raise AuditProtocolError(f"isolation.{name} must be a boolean")
        result[name] = value
    for name in _ISOLATION_ENUMS:
        value = payload.get(name, "unknown")
        if value not in ENFORCEMENT_VALUES:
            raise AuditProtocolError(f"isolation.{name} must be one of {sorted(ENFORCEMENT_VALUES)}")
        result[name] = value
    mechanism = payload.get("mechanism")
    result["mechanism"] = mechanism if mechanism in KNOWN_MECHANISMS else "unknown"
    platform = payload.get("platform")
    result["platform"] = platform if platform in KNOWN_PLATFORMS else "unknown"
    return result


def _finite_score(value: Any, label: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise AuditProtocolError(f"{label} must be a number")
    number = float(value)
    if not math.isfinite(number):
        raise AuditProtocolError(f"{label} must be finite")
    if not 0.0 <= number <= 1.0:
        raise AuditProtocolError(f"{label} must lie in [0, 1]")
    return number


def _nonnegative_int(value: Any, label: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise AuditProtocolError(f"{label} must be an integer")
    if value < 0:
        raise AuditProtocolError(f"{label} must be non-negative")
    return value


def _validate_means(payload: Any, allowed_keys: frozenset[str] | set[str], label: str) -> dict[str, float]:
    if not isinstance(payload, dict):
        raise AuditProtocolError(f"{label} must be an object")
    if len(payload) > 64:
        raise AuditProtocolError(f"{label} has too many entries")
    result: dict[str, float] = {}
    for key, value in payload.items():
        # Keys are checked against a vocabulary the parent knows independently,
        # so a mapping key cannot smuggle text across.
        if key not in allowed_keys:
            raise AuditProtocolError(f"{label} contains unknown key {key!r}")
        result[key] = _finite_score(value, f"{label}[{key}]")
    return result


def parse_audit_response(
    raw: bytes,
    expected_audit_run_id: str,
    expected_candidate_id: str,
    expected_artifact_hash: str,
    expected_identity: dict[str, Any],
    allowed_categories: frozenset[str] | set[str],
) -> dict[str, Any]:
    """Parent side: decode, validate, and correlate. Raises on any violation.

    Correlation matters as much as validation: a response that does not name the
    exact audit, candidate, and artifact that were requested is discarded rather
    than reinterpreted, so a confused or altered auditor cannot attribute a
    result to something else.
    """

    if not raw.strip():
        raise AuditProtocolError("auditor produced no response")
    if len(raw) > MAX_AUDIT_RESPONSE_BYTES:
        raise AuditProtocolError("auditor response exceeds the size cap")
    try:
        message = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise AuditProtocolError(f"auditor response is not valid JSON: {exc}") from exc
    if not isinstance(message, dict):
        raise AuditProtocolError("auditor response is not a JSON object")

    unknown = set(message) - set(RESPONSE_FIELDS)
    if unknown:
        raise AuditProtocolError(f"auditor response has unknown fields: {sorted(unknown)}")

    if message.get("protocol_version") != AUDIT_PROTOCOL_VERSION:
        raise AuditProtocolError("auditor response protocol_version mismatch")
    if message.get("kind") != KIND_AUDIT:
        raise AuditProtocolError("auditor response kind mismatch")

    for name, expected in (
        ("audit_run_id", expected_audit_run_id),
        ("candidate_id", expected_candidate_id),
        ("artifact_hash", expected_artifact_hash),
    ):
        if message.get(name) != expected:
            raise AuditProtocolError(
                f"auditor response {name} does not match the request"
            )

    status = message.get("status")
    if status not in AUDIT_STATUSES:
        raise AuditProtocolError(f"unknown audit status {status!r}")
    reason_code = message.get("reason_code")
    if reason_code not in WIRE_REASON_CODES:
        raise AuditProtocolError(f"unknown reason code {reason_code!r}")

    mismatch_field = message.get("mismatch_field")
    if mismatch_field is not None:
        if reason_code != REASON_IDENTITY_MISMATCH:
            raise AuditProtocolError("mismatch_field is only valid for an identity mismatch")
        if mismatch_field not in MISMATCH_FIELDS:
            raise AuditProtocolError(f"unknown mismatch_field {mismatch_field!r}")

    isolation = normalize_isolation(message.get("isolation") or {})

    if status == AUDIT_OK:
        if reason_code not in OK_REASON_CODES:
            raise AuditProtocolError(f"reason code {reason_code!r} cannot accompany a passing audit")
        identity = message.get("dataset_identity")
        if not isinstance(identity, dict) or identity != dict(expected_identity):
            # Equality, not similarity: the parent already knows what the
            # dataset must be, so this field carries no information and
            # therefore no channel.
            raise AuditProtocolError("auditor dataset identity does not match the recorded identity")
        holdout_score = _finite_score(message.get("holdout_score"), "holdout_score")
        num_cases = _nonnegative_int(message.get("num_cases"), "num_cases")
        if num_cases == 0:
            raise AuditProtocolError("a passing audit must report at least one case")
        safety_failures = _nonnegative_int(
            message.get("safety_failure_count"), "safety_failure_count"
        )
        if safety_failures > num_cases:
            raise AuditProtocolError("safety_failure_count exceeds num_cases")
        return {
            "status": status,
            "reason_code": reason_code,
            "mismatch_field": None,
            "holdout_score": holdout_score,
            "num_cases": num_cases,
            "safety_failure_count": safety_failures,
            "category_means": _validate_means(
                message.get("category_means"), allowed_categories, "category_means"
            ),
            "dimension_means": _validate_means(
                message.get("dimension_means"), KNOWN_DIMENSIONS, "dimension_means"
            ),
            "dataset_identity": dict(expected_identity),
            "isolation": isolation,
        }

    # Refused or failed: nothing but the reason code may be populated. A
    # non-passing audit has no score to report, so accepting one would mean
    # accepting a number with no meaning.
    if reason_code == REASON_OK:
        raise AuditProtocolError("reason code 'ok' cannot accompany a non-passing audit")
    if message.get("holdout_score") is not None:
        raise AuditProtocolError("a non-passing audit must not report a holdout score")
    if _nonnegative_int(message.get("num_cases", 0), "num_cases") != 0:
        raise AuditProtocolError("a non-passing audit must not report case counts")
    if _nonnegative_int(message.get("safety_failure_count", 0), "safety_failure_count") != 0:
        raise AuditProtocolError("a non-passing audit must not report safety counts")
    for name in ("category_means", "dimension_means", "dataset_identity"):
        value = message.get(name) or {}
        if not isinstance(value, dict) or value:
            raise AuditProtocolError(f"a non-passing audit must not populate {name}")
    if status not in (AUDIT_REFUSED, AUDIT_FAILED):
        raise AuditProtocolError(f"status {status!r} is neither passing nor a known failure")
    return {
        "status": status,
        "reason_code": reason_code,
        "mismatch_field": mismatch_field,
        "holdout_score": None,
        "num_cases": 0,
        "safety_failure_count": 0,
        "category_means": {},
        "dimension_means": {},
        "dataset_identity": {},
        "isolation": isolation,
    }
